{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app-starter.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "app-starter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
